adjective1 = input("Enter an adjective: ")
adjective2 = input("Enter another adjective: ")
type_of_bird = input("Enter a type of bird: ")
room = input("Enter a room in a house: " )
past_verb = input("Enter a verb in the past tense: ")
verb = input("Enter a verb: ")
relatives_name = input("Enter a relative's name: ")
noun1 = input("Enter a noun: " )
liquid = input("Enter a liquid: ")
verb_ing1 = input("Enter a verb ending in -ing: ")
body_pl = input("Enter a part of the body (plural): ")
noun_pl = input("Enter a plural noun: " )
verb_ing2 = input("Enter another verb ending in -ing: ")
noun2 = input("Enter another noun: " )

print("Final Story:")
print("It was a", adjective1 + ", cold November day.")
print("I woke up to the", adjective2, "smell of", type_of_bird, "roasting in the", room, "downstairs.")
print("I", past_verb, "down the stairs to see if I could help", verb, "the dinner.")
print("My mom said, see if", relatives_name, "needs a fresh", noun1 + ".")
print("So I carried a tray of glasses full of", liquid, "into the", verb_ing1, "room.")
print("When I got there, I couldn't believe my", body_pl + "!")
print("There were", noun_pl, verb_ing2, "on the", noun2 + "!")
